from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies=[('core','0001_initial')]
    operations=[
        migrations.CreateModel(
            name='RouterHotspotUser',
            fields=[
                ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),
                ('username',models.CharField(max_length=120)),('mikrotik_id',models.CharField(blank=True,max_length=120)),
                ('profile',models.CharField(blank=True,max_length=120)),('mac_address',models.CharField(blank=True,max_length=32)),
                ('comment',models.CharField(blank=True,max_length=255)),('limit_uptime',models.CharField(blank=True,max_length=80)),
                ('uptime',models.CharField(blank=True,max_length=80)),('disabled',models.BooleanField(default=False)),
                ('source',models.CharField(choices=[('mikrotik','MikroTik'),('taptap','TapTap')],default='mikrotik',max_length=20)),
                ('is_present',models.BooleanField(default=True)),('raw_data',models.JSONField(blank=True,default=dict)),
                ('last_seen_at',models.DateTimeField(default=django.utils.timezone.now)),('updated_at',models.DateTimeField(auto_now=True)),
                ('business',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='router_hotspot_users',to='core.business')),
                ('router',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='hotspot_users',to='core.router')),
            ],
        ),
        migrations.CreateModel(
            name='SyncedIPBinding',
            fields=[
                ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),
                ('mikrotik_id',models.CharField(blank=True,max_length=120)),('mac_address',models.CharField(blank=True,max_length=32)),
                ('address',models.CharField(blank=True,max_length=120)),('server',models.CharField(blank=True,max_length=120)),
                ('binding_type',models.CharField(default='bypassed',max_length=40)),('comment',models.CharField(blank=True,max_length=255)),
                ('disabled',models.BooleanField(default=False)),('source',models.CharField(choices=[('mikrotik','MikroTik'),('taptap','TapTap')],default='mikrotik',max_length=20)),
                ('sync_status',models.CharField(default='Synced',max_length=30)),('sync_error',models.TextField(blank=True)),
                ('is_present',models.BooleanField(default=True)),('raw_data',models.JSONField(blank=True,default=dict)),
                ('last_seen_at',models.DateTimeField(default=django.utils.timezone.now)),('updated_at',models.DateTimeField(auto_now=True)),
                ('business',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='synced_ip_bindings',to='core.business')),
                ('router',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='synced_ip_bindings',to='core.router')),
            ],
        ),
        migrations.CreateModel(
            name='RouterInterface',
            fields=[
                ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),
                ('name',models.CharField(max_length=120)),('default_name',models.CharField(blank=True,max_length=120)),
                ('interface_type',models.CharField(blank=True,max_length=80)),('mac_address',models.CharField(blank=True,max_length=32)),
                ('comment',models.CharField(blank=True,max_length=255)),('running',models.BooleanField(default=False)),
                ('disabled',models.BooleanField(default=False)),('mtu',models.CharField(blank=True,max_length=40)),
                ('rx_byte',models.BigIntegerField(default=0)),('tx_byte',models.BigIntegerField(default=0)),('is_present',models.BooleanField(default=True)),
                ('raw_data',models.JSONField(blank=True,default=dict)),('last_seen_at',models.DateTimeField(default=django.utils.timezone.now)),
                ('router',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='interfaces',to='core.router')),
            ],
        ),
        migrations.CreateModel(
            name='RouterNeighbor',
            fields=[
                ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),
                ('neighbor_key',models.CharField(max_length=255)),('identity',models.CharField(blank=True,max_length=180)),
                ('address',models.CharField(blank=True,max_length=120)),('mac_address',models.CharField(blank=True,max_length=32)),
                ('interface_name',models.CharField(blank=True,max_length=120)),('platform',models.CharField(blank=True,max_length=180)),
                ('board',models.CharField(blank=True,max_length=180)),('version',models.CharField(blank=True,max_length=120)),
                ('discovered_by',models.CharField(blank=True,max_length=120)),('device_kind',models.CharField(default='network',max_length=40)),
                ('is_online',models.BooleanField(default=True)),('raw_data',models.JSONField(blank=True,default=dict)),
                ('last_seen_at',models.DateTimeField(default=django.utils.timezone.now)),
                ('router',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='neighbors',to='core.router')),
            ],
        ),
        migrations.AddConstraint(model_name='routerhotspotuser',constraint=models.UniqueConstraint(fields=('router','username'),name='uniq_router_hotspot_username')),
        migrations.AddConstraint(model_name='routerinterface',constraint=models.UniqueConstraint(fields=('router','name'),name='uniq_router_interface_name')),
        migrations.AddConstraint(model_name='routerneighbor',constraint=models.UniqueConstraint(fields=('router','neighbor_key'),name='uniq_router_neighbor_key')),
    ]
