# Generated by Django 5.2.6 on 2026-09-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_security_ack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='plan_name',
            field=models.CharField(max_length=120),
        ),
    ]
