# Generated by Django 5.2.6 on 2026-09-26 15:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_voucher_plan_name_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='auto_record_sales',
            field=models.BooleanField(default=True, help_text='Record a sale automatically when an unsold voucher is first used on the router'),
        ),
        migrations.AddField(
            model_name='business',
            name='brand_color',
            field=models.CharField(default='#1769e0', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='currency',
            field=models.CharField(default='D', max_length=8),
        ),
        migrations.AddField(
            model_name='business',
            name='hotspot_url',
            field=models.CharField(blank=True, help_text='e.g. http://wifi.local/login', max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='logo_data',
            field=models.TextField(blank=True, help_text='Small logo as a data: URL'),
        ),
        migrations.AddField(
            model_name='business',
            name='monthly_revenue_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='business',
            name='support_phone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='business',
            name='wifi_ssid',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='voucher',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('wave', 'Wave'), ('qmoney', 'QMoney'), ('afrimoney', 'Afrimoney'), ('bank', 'Bank transfer'), ('card', 'Card'), ('auto', 'Auto (router activation)'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.agent')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.business')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bandwidth', 'Internet / bandwidth'), ('power', 'Electricity (NAWEC)'), ('fuel', 'Generator fuel'), ('rent', 'Rent & site fees'), ('equipment', 'Equipment'), ('salaries', 'Staff & wages'), ('maintenance', 'Repairs & maintenance'), ('marketing', 'Marketing & printing'), ('software', 'Software & licences'), ('transport', 'Transport'), ('tax', 'Tax & fees'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('wave', 'Wave'), ('qmoney', 'QMoney'), ('afrimoney', 'Afrimoney'), ('bank', 'Bank transfer'), ('card', 'Card'), ('auto', 'Auto (router activation)'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('recurring', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.business')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(blank=True, help_text='Site this cost belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.router')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('login', 'Login page'), ('redirect', 'Redirect page'), ('status', 'Status page')], default='login', max_length=20)),
                ('template_key', models.CharField(blank=True, max_length=60)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('connects', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_pages', to='core.business')),
            ],
            options={
                'ordering': ['kind', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('template_key', models.CharField(blank=True, max_length=60)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_designs', to='core.business')),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=120)),
                ('voucher_code', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('wave', 'Wave'), ('qmoney', 'QMoney'), ('afrimoney', 'Afrimoney'), ('bank', 'Bank transfer'), ('card', 'Card'), ('auto', 'Auto (router activation)'), ('other', 'Other')], default='cash', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('customer_phone', models.CharField(blank=True, max_length=60)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sold_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.agent')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.business')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.router')),
                ('voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='core.voucher')),
            ],
            options={
                'ordering': ['-sold_at'],
                'indexes': [models.Index(fields=['business', 'sold_at'], name='sale_business_date_idx')],
            },
        ),
    ]
