# Generated by Django 5.2.6 on 2026-09-26 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_finance_and_studios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherplan',
            name='price_source',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='WanSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('run_id', models.CharField(blank=True, max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Applied — waiting for confirmation'), ('active', 'Active'), ('undone', 'Undone'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('original', models.JSONField(blank=True, default=dict, help_text='Router settings before TapTap changed them, used by undo')),
                ('last_result', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('confirm_by', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('router', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wan_setup', to='core.router')),
            ],
        ),
    ]
