# Generated by Django 5.2.6 on 2026-09-27 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_wan_designer_price_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='core.agent'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='customer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='voucher',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='voucher',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='voucher',
            name='rate_limit',
            field=models.CharField(blank=True, help_text='Speed for a custom voucher with no plan, e.g. 5M/5M', max_length=50),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='core.agent'),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='settlement',
            field=models.CharField(choices=[('credit', 'On credit — agent pays as vouchers sell'), ('prepaid', 'Paid upfront — agent bought the batch')], default='credit', max_length=20),
        ),
    ]
