# Generated by Django 5.2.6 on 2026-09-27 01:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agent_batches_single_vouchers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name', max_length=120)),
                ('advertiser', models.CharField(blank=True, help_text='Who the ad is for (blank = your own promotion)', max_length=120)),
                ('advertiser_phone', models.CharField(blank=True, max_length=60)),
                ('headline', models.CharField(blank=True, max_length=120)),
                ('body', models.CharField(blank=True, max_length=280)),
                ('cta', models.CharField(blank=True, default='Learn more', max_length=40)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('image', models.TextField(blank=True, help_text='Compressed image as a data: URL so it works offline on the router')),
                ('theme', models.JSONField(blank=True, default=dict, help_text='Colours for text-only ads')),
                ('placements', models.JSONField(blank=True, default=list)),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text='Higher weight = shown more often')),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='What the advertiser pays for this campaign', max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='core.business')),
            ],
            options={
                'ordering': ['-active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AdStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.advert')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('advert', 'day'), name='uniq_ad_stat_day')],
            },
        ),
        migrations.CreateModel(
            name='DeviceSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, help_text='Your own name for this device', max_length=120)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('os', models.CharField(blank=True, max_length=60)),
                ('os_version', models.CharField(blank=True, max_length=40)),
                ('browser', models.CharField(blank=True, max_length=60)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('components', models.JSONField(blank=True, default=dict)),
                ('macs', models.JSONField(blank=True, default=list)),
                ('ips', models.JSONField(blank=True, default=list)),
                ('vouchers', models.JSONField(blank=True, default=list)),
                ('last_mac', models.CharField(blank=True, max_length=32)),
                ('last_ip', models.CharField(blank=True, max_length=64)),
                ('visits', models.PositiveIntegerField(default=1)),
                ('flagged', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_signatures', to='core.business')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_signatures', to='core.portalpage')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_signatures', to='core.router')),
            ],
            options={
                'ordering': ['-last_seen'],
                'constraints': [models.UniqueConstraint(fields=('business', 'fingerprint'), name='uniq_business_fingerprint')],
            },
        ),
    ]
