# Generated by Django 5.2.6 on 2026-09-27 02:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def set_baselines(apps, schema_editor):
    Router = apps.get_model('core', 'Router')
    Job = apps.get_model('core', 'RouterSyncJob')
    for r in Router.objects.filter(sales_baseline_at__isnull=True):
        first = Job.objects.filter(router=r, status='success').order_by('finished_at').values_list('finished_at', flat=True).first()
        if first:
            r.sales_baseline_at = first
            r.save(update_fields=['sales_baseline_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_adverts_device_signatures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='auto_enforce',
            field=models.BooleanField(default=True, help_text='Automatically disconnect sessions whose voucher has expired or been disabled'),
        ),
        migrations.AddField(
            model_name='business',
            name='enforce_grace_minutes',
            field=models.PositiveSmallIntegerField(default=5, help_text='Wait this long before fixing automatically'),
        ),
        migrations.AddField(
            model_name='business',
            name='live_sync',
            field=models.BooleanField(default=True, help_text='Check routers every few seconds for voucher, session and binding changes'),
        ),
        migrations.AddField(
            model_name='router',
            name='last_watch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='sales_baseline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SessionIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('mac_address', models.CharField(blank=True, max_length=32)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('session_id', models.CharField(blank=True, max_length=60)),
                ('reason', models.CharField(choices=[('expired', 'Voucher expired'), ('disabled', 'Voucher disabled in TapTap'), ('unknown', 'Not a TapTap or router voucher')], default='expired', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fixed', 'Fixed'), ('ended', 'Session ended by itself'), ('ignored', 'Allowed by you')], db_index=True, default='open', max_length=20)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('fix_due_at', models.DateTimeField(blank=True, null=True)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('fixed_by', models.CharField(blank=True, help_text='auto or user', max_length=20)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_incidents', to='core.business')),
                ('fixed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_incidents', to='core.router')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.voucher')),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['business', 'status'], name='incident_business_status_idx')],
            },
        ),
        migrations.RunPython(set_baselines, migrations.RunPython.noop),
]
