# Generated by Django 5.2.6 on 2026-09-27 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_missing_voucher_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(choices=[('network', 'Network equipment (switches, access points, routers)'), ('client', 'Customer & other devices'), ('any', 'Any device')], default='network', max_length=20)),
                ('match', models.CharField(choices=[('all', 'Every device'), ('cidr', 'IP range'), ('ip', 'Exact IP address'), ('ip_type', 'IP type'), ('mac', 'MAC address'), ('name', 'Name contains'), ('kind', 'Device kind')], default='all', max_length=20)),
                ('value', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(choices=[('alert', 'Alert me'), ('mute', 'Never alert')], default='alert', max_length=10)),
                ('min_offline_minutes', models.PositiveSmallIntegerField(default=3, help_text='Only alert if still offline after this long')),
                ('notify_recovery', models.BooleanField(default=True, help_text='Also tell me when it comes back online')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='core.business')),
            ],
            options={
                'ordering': ['action', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='network', max_length=20)),
                ('device_key', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=180)),
                ('ip_address', models.CharField(blank=True, max_length=120)),
                ('mac_address', models.CharField(blank=True, max_length=32)),
                ('kind', models.CharField(blank=True, max_length=30)),
                ('event', models.CharField(choices=[('offline', 'Went offline'), ('online', 'Back online')], max_length=10)),
                ('offline_since', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_alerts', to='core.business')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_alerts', to='core.router')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.alertrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True)),
                ('app', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=40)),
                ('domain', models.CharField(max_length=120)),
                ('download', models.BigIntegerField(default=0)),
                ('upload', models.BigIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usage', to='core.business')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usage', to='core.router')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'hour'], name='appusage_business_hour_idx')],
                'constraints': [models.UniqueConstraint(fields=('router', 'hour', 'app', 'domain'), name='uniq_app_usage')],
            },
        ),
        migrations.CreateModel(
            name='TrafficSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=120)),
                ('bucket', models.DateTimeField(db_index=True)),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('rx_peak_bps', models.BigIntegerField(default=0)),
                ('tx_peak_bps', models.BigIntegerField(default=0)),
                ('samples', models.PositiveIntegerField(default=0)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_samples', to='core.router')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('router', 'interface', 'bucket'), name='uniq_traffic_sample')],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('mac_address', models.CharField(blank=True, max_length=32)),
                ('hour', models.DateTimeField(db_index=True)),
                ('download', models.BigIntegerField(default=0)),
                ('upload', models.BigIntegerField(default=0)),
                ('peak_bps', models.BigIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='core.business')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='core.router')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'hour'], name='usage_business_hour_idx')],
                'constraints': [models.UniqueConstraint(fields=('router', 'username', 'mac_address', 'hour'), name='uniq_usage_record')],
            },
        ),
    ]
