# Generated by Django 5.2.6 on 2026-09-27 10:39

import django.db.models.deletion
import os
import re

from django.conf import settings
from django.db import migrations, models


def _dependencies():
    """Depend on the newest migrations that exist in THIS project, whatever they are called.

    Installations differ (merge files, locally generated migrations), so instead of
    naming one parent this finds the highest-numbered migration(s) below 0014 and
    follows all of them. That always gives Django one straight line: no
    "nonexistent parent node" and no "conflicting migrations".
    """
    here = os.path.dirname(os.path.abspath(__file__))
    found = {}
    for name in os.listdir(here):
        m = re.match(r'^(\d{4})_\w+\.py$', name)
        if m and int(m.group(1)) < 14:
            found.setdefault(int(m.group(1)), []).append(name[:-3])
    newest = max(found) if found else None
    deps = [('core', n) for n in sorted(found.get(newest, []))]
    deps.append(migrations.swappable_dependency(settings.AUTH_USER_MODEL))
    return deps


class Migration(migrations.Migration):

    dependencies = _dependencies()

    operations = [
        migrations.AddField(
            model_name='router',
            name='auto_backup',
            field=models.BooleanField(default=False, help_text='Back up the configuration automatically every night'),
        ),
        migrations.AddField(
            model_name='router',
            name='last_backup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RouterBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('backup_file', models.CharField(blank=True, help_text='Binary .backup kept on the router', max_length=160)),
                ('export_file', models.CharField(blank=True, help_text='Text .rsc export kept on the router', max_length=160)),
                ('export_size', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(blank=True, help_text='The .rsc export downloaded into TapTap (when RouterOS allows reading it)')),
                ('ros_version', models.CharField(blank=True, max_length=60)),
                ('automatic', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='core.router')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('limit', 'Speed limit'), ('guard', 'Traffic guard'), ('timed_off', 'Turned off for a while')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('limit_down_mbps', models.FloatField(default=0)),
                ('limit_up_mbps', models.FloatField(default=0)),
                ('threshold_mbps', models.FloatField(default=0)),
                ('direction', models.CharField(choices=[('down', 'Download'), ('up', 'Upload'), ('any', 'Either direction')], default='down', max_length=10)),
                ('sustain_seconds', models.PositiveIntegerField(default=60)),
                ('action', models.CharField(choices=[('throttle', 'Slow it down'), ('shutdown', 'Turn the port off')], default='throttle', max_length=20)),
                ('throttle_mbps', models.FloatField(default=2)),
                ('hold_minutes', models.PositiveIntegerField(default=10)),
                ('active', models.BooleanField(default=False, help_text='Limit applied / guard currently triggered / port currently off')),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('restore_at', models.DateTimeField(blank=True, null=True)),
                ('times_triggered', models.PositiveIntegerField(default=0)),
                ('queue_name', models.CharField(blank=True, max_length=120)),
                ('scheduler_name', models.CharField(blank=True, max_length=120)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_rules', to='core.router')),
            ],
            options={
                'ordering': ['interface', 'kind'],
                'indexes': [models.Index(fields=['router', 'interface'], name='portrule_router_iface_idx')],
            },
        ),
    ]
