# Generated by Django 5.2.6 on 2026-09-27 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_port_control_backups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, help_text='Business email for notifications (blank = your login email)', max_length=254),
        ),
        migrations.AddField(
            model_name='router',
            name='connection_mode',
            field=models.CharField(choices=[('api', 'Direct API'), ('agent', 'TapTap Link (router connects out)')], default='api', max_length=10),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40)),
                ('severity', models.CharField(default='info', max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, max_length=300)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('skipped', 'Not sent (turned off)'), ('failed', 'Failed'), ('digest', 'Waiting for digest')], db_index=True, default='queued', max_length=10)),
                ('recipients', models.CharField(blank=True, max_length=600)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('extra_recipients', models.CharField(blank=True, help_text='More addresses, separated by commas', max_length=500)),
                ('events', models.JSONField(blank=True, default=dict, help_text='event → instant | digest | off')),
                ('quiet_start', models.TimeField(blank=True, null=True)),
                ('quiet_end', models.TimeField(blank=True, null=True)),
                ('daily_summary', models.BooleanField(default=True)),
                ('summary_hour', models.PositiveSmallIntegerField(default=8)),
                ('last_digest_at', models.DateTimeField(blank=True, null=True)),
                ('last_summary_on', models.DateField(blank=True, null=True)),
                ('unsubscribe_token', models.CharField(blank=True, max_length=40)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='RouterAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_hint', models.CharField(blank=True, help_text='First characters of the token, to recognise it', max_length=12)),
                ('poll_seconds', models.PositiveSmallIntegerField(default=10)),
                ('allow_scripts', models.BooleanField(default=False, help_text='Allow custom RouterOS scripts from TapTap (off = only the built-in safe commands)')),
                ('pinned_ip', models.GenericIPAddressField(blank=True, help_text='Only accept this public IP (optional)', null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_ip', models.CharField(blank=True, max_length=64)),
                ('identity', models.CharField(blank=True, max_length=120)),
                ('ros_version', models.CharField(blank=True, max_length=60)),
                ('board', models.CharField(blank=True, max_length=80)),
                ('uptime', models.CharField(blank=True, max_length=40)),
                ('cpu_load', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('memory_free', models.BigIntegerField(blank=True, null=True)),
                ('memory_total', models.BigIntegerField(blank=True, null=True)),
                ('active_sessions', models.PositiveIntegerField(default=0)),
                ('polls', models.PositiveBigIntegerField(default=0)),
                ('router', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='core.router')),
            ],
        ),
        migrations.CreateModel(
            name='AgentCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Waiting for the router'), ('sent', 'Sent to the router'), ('done', 'Done'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_commands', to='core.router')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['router', 'status'], name='agentcmd_router_status_idx')],
            },
        ),
    ]
