# Generated by Django 5.2.6 on 2026-09-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_link_agent_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeragent',
            name='script_version',
            field=models.PositiveSmallIntegerField(default=1, help_text='Heartbeat version installed on the router'),
        ),
    ]
