# Generated by Django 5.2.6 on 2026-09-27 22:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tunnel_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(db_index=True, max_length=120)),
                ('event', models.CharField(choices=[('disabled', 'Disabled'), ('enabled', 'Enabled'), ('extended', 'Time added'), ('mac_reset', 'Devices reset'), ('enforced', 'Disconnected by enforcement'), ('router_disabled', 'Disabled on the router'), ('router_enabled', 'Enabled on the router'), ('sale_voided', 'Sale voided'), ('deleted', 'Deleted'), ('note', 'Note')], max_length=30)),
                ('source', models.CharField(choices=[('user', 'User'), ('auto', 'Automatic'), ('router', 'Router')], default='user', max_length=10)),
                ('status_before', models.CharField(blank=True, max_length=20)),
                ('status_after', models.CharField(blank=True, max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('via', models.CharField(blank=True, help_text='TapTap Link, TapTap Tunnel, Direct API or TapTap only', max_length=40)),
                ('router_result', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_events', to='core.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_events', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.voucher')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['business', 'voucher_code', 'created_at'], name='voucher_event_lookup')],
            },
        ),
    ]
