# Generated by Django 5.2.6 on 2026-09-28 00:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_email_otp_trusted_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Waiting for the router'), ('installed', 'On the router'), ('failed', 'Could not install'), ('removed', 'MikroTik default pages')], default='queued', max_length=12)),
                ('files', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(blank=True, help_text='Fingerprint of the pages, plans and branding that were installed', max_length=40)),
                ('via', models.CharField(blank=True, max_length=10)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_deployments', to='core.business')),
                ('router', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_deployment', to='core.router')),
            ],
        ),
    ]
