# Generated by Django 5.2.6 on 2026-09-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_team_roles_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='commission_percent',
            field=models.DecimalField(decimal_places=4, default=10, help_text='Up to 4 decimals, e.g. 9.09 or 9.0909', max_digits=7),
        ),
    ]
