# Generated by Django 5.2.6 on 2026-09-28 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_agent_commission_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='delete_info',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot at deletion: state, holder, removed sale'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='voucher',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='router_removal',
            field=models.CharField(blank=True, choices=[('', '—'), ('not_needed', 'Not on a router'), ('queued', 'Queued for the router'), ('removed', 'Removed from the router'), ('failed', 'Router not updated yet — retrying')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='voucher',
            name='router_removal_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='delete_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
