# Generated by Django 5.2.6 on 2026-09-28 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_voucher_code_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='shared_warning_mode',
            field=models.CharField(choices=[('manual', 'Manual — I decide'), ('auto', 'Automatic — warn at once')], default='manual', help_text='Automatic: as soon as a voucher is seen on more devices than it allows, its internet stops and the customer must accept a warning', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='shared_warning_text',
            field=models.TextField(blank=True, help_text='Shown on the warning page. Empty = TapTap default text'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='freeze_kind',
            field=models.CharField(blank=True, choices=[('freeze', 'Frozen'), ('warning', 'Warning')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='freeze_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='voucher',
            name='frozen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='frozen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='frozen_left',
            field=models.PositiveIntegerField(blank=True, help_text='Seconds left when frozen (empty: clock had not started)', null=True),
        ),
        migrations.AlterField(
            model_name='voucherevent',
            name='event',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('enabled', 'Enabled'), ('extended', 'Time added'), ('mac_reset', 'Devices reset'), ('enforced', 'Disconnected by enforcement'), ('router_disabled', 'Disabled on the router'), ('router_enabled', 'Enabled on the router'), ('sale_voided', 'Sale voided'), ('deleted', 'Deleted'), ('note', 'Note'), ('code_changed', 'Code changed'), ('frozen', 'Frozen'), ('unfrozen', 'Unfrozen'), ('warned', 'Warning sent'), ('warning_accepted', 'Warning accepted by the customer'), ('shared_resolved', 'Shared use resolved')], max_length=30),
        ),
        migrations.CreateModel(
            name='SharedUseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('fingerprints', models.JSONField(blank=True, default=list)),
                ('devices', models.PositiveSmallIntegerField(default=0)),
                ('allowed', models.PositiveSmallIntegerField(default=1)),
                ('action', models.CharField(choices=[('allowed', 'Allowed'), ('warned', 'Warning sent'), ('reset', 'Devices reset'), ('frozen', 'Frozen'), ('disabled', 'Disabled'), ('accepted', 'Customer accepted the warning')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('auto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reviews', to='core.business')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reviews', to='core.voucher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
