# Generated by Django 5.2.6 on 2026-09-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_freeze_and_shared_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherplan',
            name='is_free',
            field=models.BooleanField(default=False, help_text='No charge — vouchers of this plan are given away'),
        ),
        migrations.AlterField(
            model_name='voucherplan',
            name='duration_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('months', 'Months'), ('unlimited', 'Unlimited')], default='hours', max_length=10),
        ),
    ]
