# Generated by Django 5.2.6 on 2026-09-28 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_free_and_unlimited_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voucherplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='voucherplan',
            name='delete_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='voucherplan',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='voucherplan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherplan',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='voucherplan',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('business', 'name'), name='uniq_live_plan_name'),
        ),
    ]
