# Generated by Django 5.2.6 on 2026-09-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_plan_recycle_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='warning_message',
            field=models.TextField(blank=True, help_text='What the customer reads on the warning page (manual warning). Empty = the shared-use text'),
        ),
    ]
