# Generated by Django 5.2.6 on 2026-09-28 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_voucher_warning_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('headline', models.CharField(blank=True, help_text='Big text on the customer page', max_length=160)),
                ('description', models.TextField(blank=True, help_text='Rules / small print shown to customers')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=10)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('spins_per_voucher', models.PositiveSmallIntegerField(default=1)),
                ('require_sold', models.BooleanField(default=True, help_text='Only vouchers that were sold or used can spin (not stock on the shelf)')),
                ('theme_color', models.CharField(default='#f59e0b', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agents', models.ManyToManyField(blank=True, help_text='Shared with these agents: only their vouchers take part (empty = everyone)', related_name='bonanzas', to='core.agent')),
                ('batches', models.ManyToManyField(blank=True, help_text='Vouchers of these batches can spin', related_name='bonanzas', to='core.voucherbatch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonanzas', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plans', models.ManyToManyField(blank=True, help_text='Vouchers of these plans can spin', related_name='bonanzas', to='core.voucherplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonanzaPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('voucher', 'Free Wi-Fi voucher'), ('time', 'Extra time on their voucher'), ('cash', 'Cash / airtime'), ('gift', 'Gift at the shop'), ('none', 'No prize (try again)')], default='voucher', max_length=10)),
                ('minutes', models.PositiveIntegerField(default=0, help_text='Extra time prizes: minutes added')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Cash / airtime prizes: amount paid', max_digits=10)),
                ('details', models.CharField(blank=True, help_text='Gift description or payout note', max_length=160)),
                ('weight', models.PositiveIntegerField(default=10, help_text='Chance: bigger = more likely, compared to the other prizes')),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='How many can be won. Empty = no limit', null=True)),
                ('won', models.PositiveIntegerField(default=0)),
                ('when_out', models.CharField(choices=[('remove', 'Remove it from the wheel'), ('keep', 'Keep showing it (it can no longer be won)')], default='remove', max_length=10)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('bonanza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='core.bonanza')),
                ('plan', models.ForeignKey(blank=True, help_text='Free voucher prizes: the plan of the voucher given', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.voucherplan')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BonanzaSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=120)),
                ('prize_label', models.CharField(blank=True, max_length=60)),
                ('prize_kind', models.CharField(blank=True, max_length=10)),
                ('prize_value', models.CharField(blank=True, max_length=60)),
                ('payout', models.CharField(choices=[('none', 'Nothing to pay'), ('done', 'Given automatically'), ('pending', 'Waiting for payout'), ('paid', 'Paid out'), ('failed', 'Automatic payout failed — pay by hand')], default='none', max_length=10)),
                ('claim_code', models.CharField(blank=True, db_index=True, max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payout_note', models.CharField(blank=True, max_length=255)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bonanza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='core.bonanza')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paid_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonanza_payouts', to='core.agent')),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spins', to='core.bonanzaprize')),
                ('reward_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.voucher')),
                ('via_agent', models.ForeignKey(blank=True, help_text='Share link the customer came from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.agent')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonanza_spins', to='core.voucher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
