# Generated by Django 5.2.6 on 2026-09-28 22:37

from django.db import migrations, models


def keep_printed_numbers(apps, schema_editor):
    """Cards already printed show the old serial (the voucher id, 6 digits). Store it on those vouchers
    and continue each business's counter after its highest one, so new numbers never repeat old ones."""
    Voucher = apps.get_model('core', 'Voucher')
    Business = apps.get_model('core', 'Business')
    batch = []
    for pk in Voucher.objects.filter(serial='').values_list('pk', flat=True).iterator():
        batch.append(Voucher(pk=pk, serial=f'{pk:06d}'))
        if len(batch) >= 1000:
            Voucher.objects.bulk_update(batch, ['serial']); batch = []
    if batch:
        Voucher.objects.bulk_update(batch, ['serial'])
    from django.db.models import Max
    for b in Business.objects.all():
        top = Voucher.objects.filter(business=b).aggregate(m=Max('pk'))['m'] or 0
        b.serial_counters = {'all': top}
        b.save(update_fields=['serial_counters'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_portal_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='serial_counters',
            field=models.JSONField(blank=True, default=dict, help_text='Last number used per period'),
        ),
        migrations.AddField(
            model_name='business',
            name='serial_digits',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='business',
            name='serial_format',
            field=models.CharField(default='{n}', help_text='Pattern, e.g. KN-{yy}{mm}-{n}', max_length=60),
        ),
        migrations.AddField(
            model_name='business',
            name='serial_reset',
            field=models.CharField(choices=[('never', 'Never — one running number'), ('yearly', 'Every year'), ('monthly', 'Every month'), ('daily', 'Every day'), ('batch', 'Every batch (1, 2, 3… per batch)')], default='never', max_length=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='serial',
            field=models.CharField(blank=True, db_index=True, help_text='Printed serial number (set when the voucher is created)', max_length=60),
        ),
        migrations.RunPython(keep_printed_numbers, migrations.RunPython.noop),
    ]
