# Generated by Django 5.2.6 on 2026-09-29 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_voucher_serials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherevent',
            name='event',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('enabled', 'Enabled'), ('extended', 'Time added'), ('mac_reset', 'Devices reset'), ('enforced', 'Disconnected by enforcement'), ('router_disabled', 'Disabled on the router'), ('router_enabled', 'Enabled on the router'), ('sale_voided', 'Sale voided'), ('deleted', 'Deleted'), ('note', 'Note'), ('code_changed', 'Code changed'), ('fup_slowed', 'Slowed down (fair usage)'), ('fup_restored', 'Back to full speed'), ('fup_lifted', 'Full speed given back'), ('frozen', 'Frozen'), ('unfrozen', 'Unfrozen'), ('warned', 'Warning sent'), ('warning_accepted', 'Warning accepted by the customer'), ('shared_resolved', 'Shared use resolved')], max_length=30),
        ),
        migrations.CreateModel(
            name='FairUsagePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('period', models.CharField(choices=[('day', 'Every day (resets at midnight)'), ('week', 'Every week (resets Monday)'), ('voucher', 'Whole voucher (the plan’s full time)')], default='day', max_length=10)),
                ('counts', models.CharField(choices=[('download', 'Download only'), ('total', 'Download + upload')], default='total', max_length=10)),
                ('tiers', models.JSONField(blank=True, default=list)),
                ('free_from', models.PositiveSmallIntegerField(blank=True, help_text='Hour (0–23): data used from here…', null=True)),
                ('free_to', models.PositiveSmallIntegerField(blank=True, help_text='…until this hour does not count', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_usage_policies', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plans', models.ManyToManyField(blank=True, help_text='Empty = every plan without its own policy', related_name='fair_usage_policies', to='core.voucherplan')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FairUsageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=20)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('tier', models.PositiveSmallIntegerField(default=0, help_text='0 = full speed, 1 = first step down, …')),
                ('lifted_until', models.DateTimeField(blank=True, help_text='Full speed given back by staff until then', null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.fairusagepolicy')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fair_usage', to='core.voucher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('voucher', 'policy'), name='uniq_fup_state')],
            },
        ),
    ]
