# Generated by Django 5.2.6 on 2026-09-29 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_fair_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAppUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True)),
                ('mac', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('username', models.CharField(blank=True, db_index=True, help_text='Voucher code of the session, when known', max_length=120)),
                ('app', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=40)),
                ('domain', models.CharField(max_length=120)),
                ('download', models.BigIntegerField(default=0)),
                ('upload', models.BigIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_app_usage', to='core.business')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_app_usage', to='core.router')),
            ],
            options={
                'indexes': [models.Index(fields=['business', 'mac', 'hour'], name='devapp_mac_hour_idx')],
                'constraints': [models.UniqueConstraint(fields=('router', 'hour', 'mac', 'ip', 'app', 'domain'), name='uniq_device_app_usage')],
            },
        ),
    ]
