# Generated by Django 5.2.6 on 2026-09-29 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Fill the creator of existing rows from what TapTap already knows: router imports are
    labelled as such, and batches / single vouchers take the name from the activity log."""
    Voucher = apps.get_model('core', 'Voucher')
    VoucherBatch = apps.get_model('core', 'VoucherBatch')
    VoucherPlan = apps.get_model('core', 'VoucherPlan')
    Activity = apps.get_model('core', 'Activity')
    Router = apps.get_model('core', 'Router')
    routers = dict(Router.objects.values_list('id', 'name'))
    for p in VoucherPlan.objects.filter(source='mikrotik', created_by_label=''):
        name = routers.get(p.imported_from_router_id)
        VoucherPlan.objects.filter(pk=p.pk).update(created_by_label=f'Imported from router {name}' if name else 'Imported from router')
    for rid, name in list(routers.items()) + [(None, None)]:
        Voucher.objects.filter(source='mikrotik', created_by_label='', router_id=rid).update(
            created_by_label=f'Imported from router {name}' if name else 'Imported from router')
    for b in VoucherBatch.objects.filter(created_by_label=''):
        a = (Activity.objects.filter(business_id=b.business_id, type='Voucher Generated', details__startswith=f'Batch {b.name}:')
             .exclude(actor='').order_by('created_at').first())
        if a:
            VoucherBatch.objects.filter(pk=b.pk).update(created_by_label=a.actor[:150])
            Voucher.objects.filter(batch_id=b.pk, created_by_label='').update(created_by_label=a.actor[:150])
    for a in Activity.objects.filter(type='Voucher Created').exclude(actor='').iterator():
        code = (a.details or '').split(' ', 1)[0]
        if code:
            Voucher.objects.filter(business_id=a.business_id, code=code, created_by_label='').update(created_by_label=a.actor[:150])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_live_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='created_by_label',
            field=models.CharField(blank=True, help_text='Who created it (name and role at the time)', max_length=150),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='created_by_label',
            field=models.CharField(blank=True, help_text='Who created it (name and role at the time)', max_length=150),
        ),
        migrations.AddField(
            model_name='voucherplan',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherplan',
            name='created_by_label',
            field=models.CharField(blank=True, help_text='Who created it (name and role at the time)', max_length=150),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
