# Generated by Django 5.2.6 on 2026-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_record_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='device_lock',
            field=models.BooleanField(default=True, help_text='A voucher stays locked to the devices that first used it, until staff reset it'),
        ),
        migrations.AddField(
            model_name='business',
            name='sticky_keepalive',
            field=models.CharField(choices=[('none', 'Never — keep the session until the voucher ends'), ('30m', '30 minutes'), ('2h', '2 hours'), ('12h', '12 hours')], default='2h', help_text='How long the router keeps an unreachable device logged in (it logs back in by itself anyway)', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='sticky_sessions',
            field=models.BooleanField(default=True, help_text='Devices log back in by themselves when they come back (MAC cookie), idle devices are not logged out'),
        ),
        migrations.AddField(
            model_name='voucherdevicebinding',
            name='label',
            field=models.CharField(blank=True, help_text='Phone / laptop model when known', max_length=120),
        ),
        migrations.AddField(
            model_name='voucherdevicebinding',
            name='locked_by',
            field=models.CharField(blank=True, help_text='portal or router: where the device was first seen', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucherdevicebinding',
            name='current_mac',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='voucherdevicebinding',
            name='device_token_hash',
            field=models.CharField(blank=True, help_text='Device ID from the portal (stays the same when a phone changes its MAC)', max_length=128),
        ),
    ]
