# Generated by Django 5.2.6 on 2026-09-29 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_sticky_vouchers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fairusagestate',
            name='uniq_fup_state',
        ),
        migrations.AddField(
            model_name='fairusagestate',
            name='device',
            field=models.CharField(blank=True, default='', help_text="'' = the whole voucher; otherwise one device of a shared voucher", max_length=40),
        ),
        migrations.AddField(
            model_name='fairusagestate',
            name='device_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='fairusagestate',
            constraint=models.UniqueConstraint(fields=('voucher', 'policy', 'device'), name='uniq_fup_state_device'),
        ),
    ]
