# Generated by Django 5.2.6 on 2026-09-29 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_fair_usage_per_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairusagepolicy',
            name='bypass',
            field=models.BooleanField(default=False, help_text='Also slow down devices that get internet through an IP-binding bypass'),
        ),
        migrations.AlterField(
            model_name='fairusagestate',
            name='voucher',
            field=models.ForeignKey(blank=True, help_text='Empty for an IP-binding bypass device (device = "bypass:<MAC>")', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fair_usage', to='core.voucher'),
        ),
    ]
