# Generated by Django 5.2.6 on 2026-09-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_fair_usage_bypass'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='login_type',
            field=models.CharField(choices=[('voucher', 'Voucher'), ('member', 'Member')], db_index=True, default='voucher', max_length=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='password',
            field=models.CharField(blank=True, help_text='Member password. Empty = same as the username', max_length=64),
        ),
        migrations.AlterField(
            model_name='voucherevent',
            name='event',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('enabled', 'Enabled'), ('extended', 'Time added'), ('mac_reset', 'Devices reset'), ('enforced', 'Disconnected by enforcement'), ('router_disabled', 'Disabled on the router'), ('router_enabled', 'Enabled on the router'), ('sale_voided', 'Sale voided'), ('deleted', 'Deleted'), ('note', 'Note'), ('code_changed', 'Code changed'), ('fup_slowed', 'Slowed down (fair usage)'), ('fup_restored', 'Back to full speed'), ('fup_lifted', 'Full speed given back'), ('frozen', 'Frozen'), ('unfrozen', 'Unfrozen'), ('warned', 'Warning sent'), ('warning_accepted', 'Warning accepted by the customer'), ('shared_resolved', 'Shared use resolved'), ('password_changed', 'Password changed')], max_length=30),
        ),
    ]
