# Generated by Django 5.2.6 on 2026-09-30 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(blank=True, help_text='MikroTik port it is plugged into (empty = found automatically)', max_length=120)),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=32)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=40)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('role', models.CharField(choices=[('router', 'Router'), ('ap', 'Access point'), ('repeater', 'Repeater / mesh'), ('switch', 'Switch'), ('modem', 'Modem / ONT')], default='router', max_length=12)),
                ('mode', models.CharField(blank=True, choices=[('', 'Not sure'), ('ap', 'Access point — customers pass through to the hotspot'), ('nat', 'Router (NAT) — customers are hidden behind it')], default='', max_length=4)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('ignored', 'Not a router')], default='confirmed', max_length=12)),
                ('source', models.CharField(choices=[('auto', 'Found automatically'), ('ip', 'Added by IP'), ('manual', 'Added by hand')], default='auto', max_length=8)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_routers', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Another site router it is connected to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.siterouter')),
                ('router', models.ForeignKey(blank=True, help_text='The MikroTik it hangs from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_routers', to='core.router')),
            ],
            options={
                'ordering': ['name', 'ip_address'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mac_address', ''), _negated=True), fields=('business', 'mac_address'), name='uniq_site_router_mac')],
            },
        ),
    ]
