# Generated by Django 5.2.6 on 2026-09-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_site_routers'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterouter',
            name='probe',
            field=models.JSONField(blank=True, default=dict, help_text='Last probe through the MikroTik (core/router_probe.py)'),
        ),
        migrations.AddField(
            model_name='siterouter',
            name='probed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
