# Generated by Django 5.2.6 on 2026-09-30 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_resend_unlimited_vouchers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherevent',
            name='event',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('enabled', 'Enabled'), ('extended', 'Time added'), ('mac_reset', 'Devices reset'), ('enforced', 'Disconnected by enforcement'), ('router_disabled', 'Disabled on the router'), ('router_enabled', 'Enabled on the router'), ('sale_voided', 'Sale voided'), ('deleted', 'Deleted'), ('note', 'Note'), ('code_changed', 'Code changed'), ('fup_slowed', 'Slowed down (fair usage)'), ('fup_restored', 'Back to full speed'), ('fup_lifted', 'Full speed given back'), ('frozen', 'Frozen'), ('unfrozen', 'Unfrozen'), ('warned', 'Warning sent'), ('warning_accepted', 'Warning accepted by the customer'), ('shared_resolved', 'Shared use resolved'), ('password_changed', 'Password changed'), ('time_up', 'Time ran out — switched off')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['status', 'expires_at'], name='voucher_status_expires'),
        ),
    ]
