# Generated by Django 5.2.6 on 2026-10-01 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_strict_voucher_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('stock_low', 'Voucher stock is low'), ('stock_restocked', 'Voucher stock is back (restocked)'), ('no_sales', 'No sale for a while'), ('daily_revenue', 'Today’s sales reached an amount'), ('router_offline', 'A router is offline'), ('online_high', 'Many customers online at once'), ('agent_debt', 'An agent owes more than an amount'), ('members_expiring', 'Members are about to expire'), ('fup_slowed', 'Customers slowed by fair usage')], max_length=30)),
                ('params', models.JSONField(blank=True, default=dict, help_text='threshold, plan, router, hours, amount…')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Urgent')], default='warning', max_length=10)),
                ('bell', models.BooleanField(default=True)),
                ('sound', models.BooleanField(default=True)),
                ('desktop', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=False)),
                ('repeat_hours', models.PositiveSmallIntegerField(default=0, help_text='Remind again every N hours while it is still true (0 = once)')),
                ('quiet_from', models.PositiveSmallIntegerField(blank=True, help_text='No sound / desktop pop-up from this hour…', null=True)),
                ('quiet_to', models.PositiveSmallIntegerField(blank=True, help_text='…until this hour (the bell still counts it)', null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('firing', models.BooleanField(default=False, help_text='The condition is true right now')),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_value', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rules', to='core.business')),
            ],
            options={
                'ordering': ['-enabled', 'kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=30)),
                ('level', models.CharField(default='warning', max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('sound', models.BooleanField(default=True)),
                ('desktop', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_alerts', to='core.business')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.eventrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
