# Generated by Django 5.2.6 on 2026-10-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_security_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrule',
            name='kind',
            field=models.CharField(choices=[('stock_low', 'Voucher stock is low'), ('stock_restocked', 'Voucher stock is back (restocked)'), ('no_sales', 'No sale for a while'), ('daily_revenue', 'Today’s sales reached an amount'), ('router_offline', 'A router is offline'), ('online_high', 'Many customers online at once'), ('agent_debt', 'An agent owes more than an amount'), ('agent_stock_low', 'An agent is running out of vouchers'), ('agent_collection_due', 'An agent has not handed in cash for a while'), ('agent_collected', 'An agent handed in cash'), ('members_expiring', 'Members are about to expire'), ('fup_slowed', 'Customers slowed by fair usage')], max_length=30),
        ),
    ]
