# Generated by Django 5.2.6 on 2026-10-01 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_agent_alerts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='peak_days',
            field=models.JSONField(blank=True, default=list, help_text='Days with peak hours; empty = every day'),
        ),
        migrations.AddField(
            model_name='business',
            name='peak_from',
            field=models.TimeField(blank=True, help_text='Peak hours start (e.g. 18:00)', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='peak_to',
            field=models.TimeField(blank=True, help_text='Peak hours end (e.g. 23:00)', null=True),
        ),
        migrations.CreateModel(
            name='AppControlState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(blank=True, max_length=64)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('router', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_control', to='core.router')),
            ],
        ),
        migrations.CreateModel(
            name='AppRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('services', models.JSONField(default=list, help_text='Service keys from core/app_catalog.py')),
                ('custom_domains', models.JSONField(blank=True, default=list, help_text='Extra sites, e.g. ["example.com"]')),
                ('action', models.CharField(choices=[('block', 'Block'), ('slow', 'Slow down'), ('allow', 'Always allow')], default='block', max_length=10)),
                ('down_mbps', models.DecimalField(decimal_places=2, default=1, help_text='Slow down: download speed per device', max_digits=7)),
                ('up_mbps', models.DecimalField(decimal_places=2, default=1, help_text='Slow down: upload speed per device', max_digits=7)),
                ('when', models.CharField(choices=[('always', 'All day'), ('window', 'Between set hours'), ('peak', 'Peak hours'), ('offpeak', 'Off-peak hours')], default='always', max_length=10)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('days', models.JSONField(blank=True, default=list, help_text='["mon","tue",…]; empty = every day')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Temporary rules: starts', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Temporary rules: ends (empty = permanent)', null=True)),
                ('scope', models.CharField(choices=[('customers', 'Logged-in hotspot customers'), ('everyone', 'Everyone on the router')], default='customers', max_length=10)),
                ('block_quic', models.BooleanField(default=True, help_text='Also stop QUIC (UDP 443) for these services so the rule catches all their traffic')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_rules', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('routers', models.ManyToManyField(blank=True, help_text='Empty = every router', related_name='app_rules', to='core.router')),
            ],
            options={
                'ordering': ['action', 'name'],
            },
        ),
    ]
