# Generated by Django 5.2.6 on 2026-10-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_voucher_archive_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='router_profile',
            field=models.CharField(blank=True, help_text='Hotspot user profile chosen by hand for this voucher (empty = from its plan)', max_length=120),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('expired', 'Expired'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
