# Generated by Django 5.2.6 on 2026-10-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_traffic_speed_bypass_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusage',
            name='via',
            field=models.CharField(blank=True, default='', help_text='CDN that delivered it (Fastly, Akamai, Cloudflare…)', max_length=40),
        ),
        migrations.AddField(
            model_name='deviceappusage',
            name='via',
            field=models.CharField(blank=True, default='', help_text='CDN that delivered it (Fastly, Akamai, Cloudflare…)', max_length=40),
        ),
    ]
