# Generated by Django 5.2.6 on 2026-10-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_usage_via_cdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='portal_token',
            field=models.CharField(blank=True, db_index=True, help_text="Secret in the agent's QR code (voucher checker)", max_length=40),
        ),
    ]
