# Generated by Django 5.2.6 on 2026-10-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_agent_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Number the voucher checker tells customers to call (empty = the customer help line in Settings)', max_length=60),
        ),
    ]
