# Generated by Django 5.2.6 on 2026-10-03 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_agent_customer_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered', models.CharField(help_text='What the agent typed or scanned (shortened)', max_length=60)),
                ('result', models.CharField(help_text='unused / in_use / finished / unknown', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='core.agent')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_checks', to='core.business')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_checks', to='core.voucher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='core.agent')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_help', to='core.business')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_help', to='core.voucher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('done', 'Vouchers made'), ('rejected', 'Declined')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.agent')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_orders', to='core.voucherbatch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_orders', to='core.business')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_orders', to='core.voucherplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
