# Generated by Django 5.2.6 on 2026-10-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_agent_logs_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='order_plans',
            field=models.ManyToManyField(blank=True, help_text='Plans this agent may order on the voucher checker (none ticked = every active plan)', related_name='orderable_by', to='core.voucherplan'),
        ),
    ]
