# Generated by Django 5.2.6 on 2026-10-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_agent_order_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='order_quantity',
            field=models.PositiveIntegerField(default=10, help_text='How many vouchers an order starts with on the voucher checker'),
        ),
        migrations.AddField(
            model_name='agent',
            name='order_quantity_fixed',
            field=models.BooleanField(default=False, help_text='The agent always orders exactly this many (cannot change it)'),
        ),
    ]
