# Generated by Django 5.2.6 on 2026-10-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_voucher_entry_security'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='voucherentrydevice',
            new_name='core_vouche_busines_c732e9_idx',
            old_name='core_vouche_busines_81cb39_idx',
        ),
        migrations.RenameIndex(
            model_name='voucherentrydevice',
            new_name='core_vouche_busines_8fd805_idx',
            old_name='core_vouche_busines_b81a67_idx',
        ),
        migrations.AddField(
            model_name='router',
            name='uplink_ignored',
            field=models.JSONField(blank=True, default=list, help_text='Router ids whose "looks connected" suggestion was dismissed'),
        ),
        migrations.AddField(
            model_name='router',
            name='uplink_internet',
            field=models.BooleanField(default=False, help_text='Placed straight on the Internet by the owner'),
        ),
        migrations.AddField(
            model_name='router',
            name='uplink_port',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='router',
            name='uplink_router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downlinks', to='core.router'),
        ),
        migrations.AddField(
            model_name='router',
            name='uplink_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downlinks', to='core.siterouter'),
        ),
    ]
