# Generated by Django 5.2.6 on 2026-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_router_uplinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='hotspot_dns_name',
            field=models.CharField(blank=True, default='login.wifi', help_text='Easy address customers can type to open the login page (http://login.wifi). Set on routers whose hotspot has none.', max_length=60),
        ),
    ]
