# Generated by Django 5.2.6 on 2026-10-04 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_hotspot_dns_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventalert',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Only this person sees it (tracking); empty = everyone', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('plan', 'Plan'), ('batch', 'Batch'), ('voucher', 'Voucher')], max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('label', models.CharField(help_text='Name shown in alerts (kept if the item is renamed or deleted)', max_length=160)),
                ('mode', models.CharField(choices=[('all', 'Everything'), ('some', 'Only what I choose')], default='all', max_length=6)),
                ('events', models.JSONField(blank=True, default=list)),
                ('channel', models.CharField(choices=[('app', 'In the app'), ('app_email', 'In the app and by email')], default='app', max_length=10)),
                ('note', models.CharField(blank=True, help_text='Why you track it (shown in each alert)', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='core.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taptap_watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'object_id'), name='uniq_watch_user_item')],
            },
        ),
    ]
