# Generated by Django 5.2.6 on 2026-10-04 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=120)),
                ('mac', models.CharField(db_index=True, max_length=32)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('peak', models.PositiveSmallIntegerField(default=0)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('suspected', 'Suspected'), ('warned', 'Warned'), ('blocked', 'Blocked'), ('trusted', 'Trusted'), ('cleared', 'Cleared')], default='suspected', max_length=10)),
                ('action_taken', models.CharField(blank=True, max_length=40)),
                ('times', models.PositiveIntegerField(default=1, help_text='How many times it was detected')),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_cases', to='core.business')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.router')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharing_cases', to='core.voucher')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='SharingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('monitor', 'Monitor only — just tell me'), ('warn', 'Warn the customer'), ('block', 'Block sharing'), ('escalate', 'Warn first, block if it happens again')], default='monitor', max_length=10)),
                ('threshold', models.PositiveSmallIntegerField(default=80, help_text='Score (0–100) that triggers the action')),
                ('suspect_at', models.PositiveSmallIntegerField(default=40, help_text='Score from which a device is listed as suspected')),
                ('block_minutes', models.PositiveSmallIntegerField(default=30)),
                ('message', models.TextField(default='This voucher is for one device only. Internet sharing, mobile hotspot, tethering or connecting another router is not allowed. Please disconnect the shared connection and reconnect this device.', max_length=600)),
                ('single_device_only', models.BooleanField(default=True, help_text='Only check vouchers allowing one device')),
                ('notify', models.CharField(choices=[('none', 'Don’t notify me'), ('app', 'In the app'), ('app_email', 'In the app and by email')], default='app', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_policy', to='core.business')),
                ('exempt_plans', models.ManyToManyField(blank=True, related_name='+', to='core.voucherplan')),
            ],
        ),
        migrations.CreateModel(
            name='SharingTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=32)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_trust', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business', 'mac'), name='uniq_sharing_trust')],
            },
        ),
    ]
