# Generated by Django 5.2.6 on 2026-10-04 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_sharing_protection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesignature',
            name='blacklist_hits',
            field=models.PositiveIntegerField(default=0, help_text='Times it tried to use a voucher or connect while blacklisted'),
        ),
        migrations.AddField(
            model_name='devicesignature',
            name='blacklist_last_hit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicesignature',
            name='blacklist_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='devicesignature',
            name='blacklisted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='devicesignature',
            name='blacklisted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicesignature',
            name='flag_level',
            field=models.CharField(blank=True, choices=[('watch', 'Watch'), ('suspect', 'Suspicious'), ('danger', 'Dangerous')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='devicesignature',
            name='flag_notify',
            field=models.BooleanField(default=False, help_text='Tell me when this flagged device enters a voucher or comes online'),
        ),
        migrations.AddField(
            model_name='devicesignature',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicesignature',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
