# Generated by Django 5.2.6 on 2026-10-04 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_device_blacklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(blank=True, max_length=60)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('kind', models.CharField(choices=[('router', 'Router'), ('ap', 'Access point'), ('switch', 'Switch'), ('other', 'Other')], default='router', max_length=10)),
                ('ip', models.GenericIPAddressField(help_text='Its address on your network, e.g. 192.168.88.20')),
                ('mac', models.CharField(blank=True, max_length=32)),
                ('web_port', models.PositiveIntegerField(default=80)),
                ('web_https', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=80)),
                ('password_enc', models.TextField(blank=True, help_text='Encrypted admin password')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('omada_mac', models.CharField(blank=True, help_text='Same device in the Omada controller (if any)', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_devices', to='core.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(blank=True, help_text='The MikroTik it sits behind (TapTap reaches it through this router)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_devices', to='core.router')),
            ],
            options={
                'ordering': ['router__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OmadaController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(help_text='e.g. https://192.168.88.10:8043 or the Omada Cloud northbound URL', max_length=200)),
                ('omadac_id', models.CharField(max_length=80)),
                ('client_id', models.CharField(max_length=120)),
                ('client_secret_enc', models.TextField(blank=True)),
                ('site_id', models.CharField(blank=True, max_length=80)),
                ('site_name', models.CharField(blank=True, max_length=120)),
                ('verify_ssl', models.BooleanField(default=False, help_text='Local controllers use a self-signed certificate')),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='omada', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=48, unique=True)),
                ('mode', models.CharField(choices=[('proxy', 'Through TapTap (tunnel)'), ('direct', 'Direct to the router (your address only)')], max_length=10)),
                ('port', models.PositiveIntegerField()),
                ('target_host', models.CharField(help_text='Where TapTap / the browser connects (tunnel IP or public IP)', max_length=120)),
                ('client_ip', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.netdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
