# Generated by Django 5.2.6 on 2026-10-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_other_routers'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotesession',
            name='command_id',
            field=models.PositiveIntegerField(blank=True, help_text='TapTap Link command that opens the path', null=True),
        ),
    ]
