# Generated by Django 5.2.6 on 2026-10-04 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remote_session_command'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='geo_accuracy',
            field=models.PositiveIntegerField(blank=True, help_text='metres, from the phone that mapped it', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='geo_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='geo_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='router',
            name='geo_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='geo_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='geo_note',
            field=models.CharField(blank=True, help_text='e.g. pole behind the bakery, 6 m up', max_length=160),
        ),
        migrations.AddField(
            model_name='siterouter',
            name='geo_accuracy',
            field=models.PositiveIntegerField(blank=True, help_text='metres, from the phone that mapped it', null=True),
        ),
        migrations.AddField(
            model_name='siterouter',
            name='geo_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterouter',
            name='geo_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siterouter',
            name='geo_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterouter',
            name='geo_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterouter',
            name='geo_note',
            field=models.CharField(blank=True, help_text='e.g. pole behind the bakery, 6 m up', max_length=160),
        ),
    ]
