# Generated by Django 5.2.6 on 2026-10-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_cash_collection_allocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_minutes',
            field=models.PositiveSmallIntegerField(choices=[(15, 'Every 15 minutes'), (30, 'Every 30 minutes'), (60, 'Every hour'), (120, 'Every 2 hours'), (240, 'Every 4 hours'), (360, 'Every 6 hours'), (720, 'Twice a day'), (1440, 'Once a day')], default=60, help_text='How often the digest email is sent'),
        ),
    ]
