# Generated by Django 5.2.6 on 2026-10-10 15:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_voucher_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(choices=[('fixed', 'Fixed monthly salary'), ('sales', '% of sales'), ('profit', '% of profit')], default='fixed', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Monthly salary (fixed) or basic pay on top of a percentage deal', max_digits=12)),
                ('percent', models.DecimalField(decimal_places=4, default=0, help_text='Share of sales or profit, 0–100', max_digits=7)),
                ('minimum', models.DecimalField(decimal_places=2, default=0, help_text='Guaranteed pay for a full month (0 = none)', max_digits=12)),
                ('cap', models.DecimalField(decimal_places=2, default=0, help_text='Most they can earn in a month (0 = no cap)', max_digits=12)),
                ('method', models.CharField(default='cash', help_text='Usual way they are paid', max_length=20)),
                ('pay_day', models.PositiveSmallIntegerField(default=28, help_text='Day of the month pay is due')),
                ('starts_on', models.DateField(blank=True, help_text='Pay counts from this date', null=True)),
                ('show_basis', models.BooleanField(default=False, help_text='Let the staff member see the sales / profit figure on My pay')),
                ('active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_pay', to='core.business')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='core.teammember')),
                ('site', models.ForeignKey(blank=True, help_text="Count only this site's sales / profit (blank = whole business)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.router')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['member__user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(help_text='Kept so history survives removing the member', max_length=150)),
                ('month', models.DateField(db_index=True, help_text='First day of the month this payment is for')),
                ('kind', models.CharField(choices=[('salary', 'Salary'), ('advance', 'Advance'), ('bonus', 'Bonus'), ('deduction', 'Deduction')], default='salary', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('calc', models.JSONField(blank=True, default=dict, help_text='How the pay was worked out when this was recorded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_payouts', to='core.business')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_payout', to='core.expense')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='core.teammember')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
                'indexes': [models.Index(fields=['business', 'month'], name='core_staffp_busines_837de3_idx')],
            },
        ),
    ]
