# Generated by Django 5.2.6 on 2026-10-10 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_wan_isp_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='freeze_planned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='freeze_planned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='freeze_planned_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='voucherevent',
            name='event',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('enabled', 'Enabled'), ('extended', 'Time added'), ('mac_reset', 'Devices reset'), ('enforced', 'Disconnected by enforcement'), ('router_disabled', 'Disabled on the router'), ('router_enabled', 'Enabled on the router'), ('sale_voided', 'Sale voided'), ('deleted', 'Deleted'), ('note', 'Note'), ('code_changed', 'Code changed'), ('fup_slowed', 'Slowed down (fair usage)'), ('fup_restored', 'Back to full speed'), ('fup_lifted', 'Full speed given back'), ('frozen', 'Frozen'), ('unfrozen', 'Unfrozen'), ('warned', 'Warning sent'), ('warning_accepted', 'Warning accepted by the customer'), ('shared_resolved', 'Shared use resolved'), ('password_changed', 'Password changed'), ('time_up', 'Time ran out — switched off'), ('rolled_back', 'Rolled back to full time'), ('time_shortened', 'End time moved earlier'), ('freeze_planned', 'Freeze planned'), ('freeze_plan_cancelled', 'Planned freeze cancelled')], max_length=30),
        ),
    ]
